- name: Common tool setup on all the servers
  hosts: appsrvgrp
  become: yes
  vars:
    tom_url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72.tar.gz
    tomcat_home: /usr/local/tomcat9

  tasks:
    - name: Install JDK 17 on CentOS 9
      yum:
        name: java-17-openjdk
        state: present
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '9'

    - name: Download Tomcat 9 Tar Ball/Binaries
      get_url:
        url: "{{ tom_url }}"
        dest: /tmp/tomcat-9.tar.gz

    - name: Add tomcat group
      group:
        name: tomcat
        state: present

    - name: Add tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/nologin
        home: "{{ tomcat_home }}"

    - name: Create tomcat installation directory
      file:
        path: "{{ tomcat_home }}"
        state: directory

    - name: Extract Tomcat 9
      unarchive:
        src: /tmp/tomcat-9.tar.gz
        dest: /tmp/
        remote_src: yes
      register: unarchive_info

    - debug:
        msg: "Extracted folder: {{ unarchive_info.files[0].split('/')[0] }}"

    - name: Move Tomcat files to installation directory
      command: mv "/tmp/{{ unarchive_info.files[0].split('/')[0] }}" "{{ tomcat_home }}"

    - name: Change ownership of Tomcat directory
      file:
        path: "{{ tomcat_home }}"
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Set up systemd service file for Tomcat 9
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat 9
          After=network.target

          [Service]
          Type=forking

          User=tomcat
          Group=tomcat

          Environment="JAVA_HOME=/usr/lib/jvm/java-17-openjdk"
          Environment="CATALINA_HOME={{ tomcat_home }}"
          Environment="CATALINA_BASE={{ tomcat_home }}"
          Environment="CATALINA_PID={{ tomcat_home }}/temp/tomcat.pid"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          Environment="JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"

          ExecStart={{ tomcat_home }}/bin/startup.sh
          ExecStop={{ tomcat_home }}/bin/shutdown.sh

          [Install]
          WantedBy=multi-user.target
      mode: "0644"

    - name: Reload systemd configuration
      systemd:
        daemon_reload: yes

    - name: Start and enable Tomcat 9
      service:
        name: tomcat
        state: started
        enabled: yes
